### ISSUE TITLE
Crush on game start

### ISSUE THREAD

**Issue by AugustKaro** [aki-art/ONI-Asphalt-Tile#1]
[output_log.txt](https://github.com/aki-art/ONI-Asphalt-Tile/files/4118694/output_log.txt)
i think its something to do with translation? maybe?

**Comment by aki-art** [comment]
Please try unsubscribing and resubscribing, that may fix the issue.
This is a bug that happens rarely with steam installing a mod, there is nothing i can do about it.

If that doesnt work, try installing the mod manually from [the releases.](https://github.com/aki-art/ONI-Asphalt-Tile/releases/tag/v1.1), by just dropping the files in it into a "local" folder in your mods folder.

**Comment by AugustKaro** [comment]
Please try unsubscribing and resubscribing, that may fix the issue. did not.
I did it first even before writing to you, even manually deleted all the folders and restarted the game without this mod. But after installing manually from the archive it seems to work ok.

**Comment by aki-art** [comment]
I'm sorry for the inconvenience . But I'm glad to hear it works with manual install.

**Comment by aki-art** [comment]
> Please try unsubscribing and resubscribing, that may fix the issue. did not.
> I did it first even before writing to you, even manually deleted all the folders and restarted the game without this mod. But after installing manually from the archive it seems to work ok.

Hey. it's beeen a while, but it is possible Steam version could work for you now, if you use Stephens Mod Updater to force the update: https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283
